const nameCache = 'bogotajs-cache2';

self.addEventListener('install', function(event) {
  event.waitUntil(
    caches.open(nameCache).then(function(cache) {
      // Get the assets manifest so we can see what our js file is named
      // This is because webpack hashes it
      fetch('./asset-manifest.json')
        .then(response => {
          return response.json();
        })
        .then(assets => {
          console.log(assets);
          // Open a cache and cache our files
          // We want to cache the page and the main.js generated by webpack
          // We could also cache any static assets like CSS or images
          const urlsToCache = ['/', assets['app.js'], assets['app.css']];
          cache.addAll(urlsToCache);
          console.log('cached');
        });
    })
  );
});

self.addEventListener('activate', function(event) {
  var cacheWhitelist = [nameCache];
  event.waitUntil(
    caches.keys().then(function(keys) {
      return Promise.all(
        keys.map(function(key) {
          console.log(!cacheWhitelist.includes(key));
          if (!cacheWhitelist.includes(key)) {
            return caches.delete(key);
          }
        })
      );
    })
  );
});

self.addEventListener('fetch', function(event) {
  // Ignore non-get request like when accessing the admin panel
  if (event.request.method !== 'GET') {
    return;
  }
  // Don't try to handle non-secure assets because fetch will fail
  // Here's where we cache all the things!
  event.respondWith(
    caches.open('bogotajs-cache').then(function(cache) {
      return fetch(event.request)
        .then(function(networkResponse) {
          console.log('with internet', networkResponse);
          cache.put(event.request, networkResponse.clone());
          return networkResponse;
        })
        .catch(function() {
          console.log('without internet', cache.match(event.request));
          return cache.match(event.request);
        });
    })
  );
});

if ('serviceWorker' in navigator) {
  fetch('./asset-manifest.json')
    .then(response => {
      return response.json();
    })
    .then(assets => {
      navigator.serviceWorker
        .register(assets['worker.js'])
        .then(
          function(registration) {
            console.log('congratulations');
          },
          function(err) {
            // registration failed :(
          }
        )
        .catch(function(err) {});
    });
} else {
  // Service worker  not support
}
